In [10]:
# Import libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

In [11]:
# Load dataset
df = pd.read_csv("/content/healthcare_dataset (1).csv")

In [12]:
# Drop 'Loan_ID' column
df.drop(columns=['Name'], inplace=True)

In [13]:
df

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [14]:
# Fill missing values
# Fill categorical columns with mode
categorical_cols = ['Gender', 'Blood Type', 'Medical Condition', 'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider', 'Room Number', 'Admission Type', 'Discharge Date', 'Medication', 'Test Results']
for col in categorical_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

<ipython-input-14-3c2a1d011c47>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
<ipython-input-14-3c2a1d011c47>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [15]:
print(df.columns)
numerical_cols = ['Age', 'Billing Amount', 'Room Number', 'Length of Stay'] # Example: Changed to 'Length of Stay' based on a common pattern
for col in numerical_cols:
    if col in df.columns:
        df[col].fillna(df[col].median(), inplace=True)
    else:
        print(f"Warning: Column '{col}' not found in DataFrame.")

Index(['Age', 'Gender', 'Blood Type', 'Medical Condition', 'Date of Admission',
       'Doctor', 'Hospital', 'Insurance Provider', 'Billing Amount',
       'Room Number', 'Admission Type', 'Discharge Date', 'Medication',
       'Test Results'],
      dtype='object')
Warning: Column 'Length of Stay' not found in DataFrame.

<ipython-input-15-e4364bdeea7d>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 55500 non-null  int64
 1   Gender              55500 non-null  object
 2   Blood Type          55500 non-null  object
 3   Medical Condition   55500 non-null  object
 4   Date of Admission   55500 non-null  object
 5   Doctor              55500 non-null  object
 6   Hospital            55500 non-null  object
 7   Insurance Provider  55500 non-null  object
 8   Billing Amount      55500 non-null  float64
 9   Room Number         55500 non-null  int64
 10  Admission Type      55500 non-null  object
 11  Discharge Date      55500 non-null  object
 12  Medication          55500 non-null  object
 13  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 5.9+ MB

In [17]:
# Convert categorical values to numeric using .replace()
df['Gender'] = df['Gender'].replace({'Male': 1, 'Female': 0})
df['Blood Type'] = df['Blood Type'].replace({'A+':0, 'A-':1, 'B+':2, 'B-':3, 'AB+':4, 'AB-':5, 'O+':6, 'O-':7})
df['Medical Condition'] = df['Medical Condition'].replace({'Cancer':0, 'Obesity':1, 'Diabetes':2})
df['Admission Type'] = df['Admission Type'].replace({'Urgent':0, 'Emergency':1, 'Elective':2})
df['Test Results'] = df['Test Results'].replace({'Normal':0, 'Abnormal':1, 'Inconclusive':2})
display(df.head())

<ipython-input-17-e97e29bb1421>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender'] = df['Gender'].replace({'Male': 1, 'Female': 0})
<ipython-input-17-e97e29bb1421>:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Blood Type'] = df['Blood Type'].replace({'A+':0, 'A-':1, 'B+':2, 'B-':3, 'AB+':4, 'AB-':5, 'O+':6, 'O-':7})
<ipython-input-17-e97e29bb1421>:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Admission Type'] = df['Admission Type'].replace({'Urgent':0, 'Emergency':1, 'Elective':2})
<ipython-input-17-e97e29bb1421>:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Test Results'] = df['Test Results'].replace({'Normal':0, 'Abnormal':1, 'Inconclusive':2})

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,30,1,3,0,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,0,2024-02-02,Paracetamol,0
1,62,1,0,1,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,1,2019-08-26,Ibuprofen,2
2,76,0,1,1,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,1,2022-10-07,Aspirin,0
3,28,0,6,2,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,2,2020-12-18,Ibuprofen,1
4,43,0,4,0,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,0,2022-10-09,Penicillin,1

In [24]:
df['Arthritis'] = pd.to_numeric(df['Arthritis'], errors='coerce')

KeyError: 'Arthritis'

In [19]:
# Split into features and target
X = df.drop('Test Results', axis=1)
y = df['Test Results']

In [20]:
y

0        0
1        2
2        0
3        1
4        1
        ..
55495    1
55496    0
55497    1
55498    1
55499    1
Name: Test Results, Length: 55500, dtype: int64

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

In [22]:
y_test

31641    2
9246     1
1583     2
36506    1
11259    2
        ..
30799    2
36334    1
43559    1
31579    0
18532    1
Name: Test Results, Length: 5550, dtype: int64

In [23]:
# Train the model
model = LogisticRegression()
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'Arthritis'

# Task
column convert string to float

Here is all the data you need:
"healthcare_dataset (1).csv"

## Data loading

### Subtask:
Load the healthcare dataset.

**Reasoning**:
Load the healthcare dataset and display basic information.

In [ ]:
import pandas as pd

try:
    df = pd.read_csv('healthcare_dataset (1).csv')
    display(df.head())
    print(df.shape)
    print(df.dtypes)
except FileNotFoundError:
    print("Error: 'healthcare_dataset (1).csv' not found.")
except pd.errors.ParserError:
    print("Error: Unable to parse the CSV file.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

## Data exploration

### Subtask:
Identify string columns that represent numerical data and require conversion to float.

**Reasoning**:
Inspect the object columns to identify those that might represent numerical data, and create a list of column names to convert.

In [ ]:
# Inspect object columns for potential numeric data
potential_numeric_cols = []
for col in df.columns:
    if df[col].dtype == 'object':
        # Inspect a sample of values
        sample_values = df[col].unique()[:10]  # Check first 10 unique values
        is_numeric = True
        for val in sample_values:
            try:
                float(val)
            except ValueError:
                is_numeric = False
                break
        if is_numeric and col not in ['Name', 'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider', 'Admission Type', 'Discharge Date', 'Medical Condition', 'Medication', 'Test Results']:
            potential_numeric_cols.append(col)
            print(f"Column '{col}' appears to contain numeric data.")
        else:
            print(f"Column '{col}' does not appear to contain numeric data.")

# Print the list of potential numeric columns
print(f"\nPotential Numeric Columns: {potential_numeric_cols}")

## Data cleaning

### Subtask:
Handle inconsistencies in the identified columns.

**Reasoning**:
No string columns were identified as containing numerical data in the previous step.  Therefore, no conversion is necessary.  I will print a message indicating this and finish the task.

In [ ]:
print("No string columns identified as containing numerical data. No conversion needed.")

## Data wrangling

### Subtask:
Convert identified string columns to float (Retry 1)

**Reasoning**:
Re-examine the columns identified in the previous data exploration step with a larger sample size and convert the columns to float if possible. Fill NaN values with column means.

In [ ]:
potential_numeric_cols = []
for col in df.columns:
    if df[col].dtype == 'object':
        # Inspect a larger sample of values (e.g., 100 unique values)
        sample_values = df[col].unique()[:100]
        is_numeric = True
        for val in sample_values:
            try:
                float(val)
            except ValueError:
                is_numeric = False
                break
        if is_numeric and col not in [ 'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider', 'Admission Type', 'Discharge Date', 'Medical Condition', 'Medication', 'Test Results']:
            potential_numeric_cols.append(col)
            print(f"Column '{col}' appears to contain numeric data.")

if potential_numeric_cols:
    for col in potential_numeric_cols:
        try:
            df[col] = pd.to_numeric(df[col], errors='coerce')
            df[col] = df[col].fillna(df[col].mean())
        except (ValueError, TypeError):
            print(f"Error converting column '{col}' to numeric.")

    print("\nData types of updated columns:")
    print(df[potential_numeric_cols].dtypes)
else:
    print("No columns identified for conversion.")

## Data exploration

### Subtask:
Verify the data type conversions and check for anomalies.

**Reasoning**:
Verify the data types of the columns that were supposed to be converted to numeric and check for anomalies in their distributions.

In [ ]:
# Check data types of columns that *should* have been converted
columns_to_check = ['Billing Amount', 'Room Number']  # Replace with the columns you actually tried to convert

# Check for existence before proceeding.
for col in columns_to_check:
    if col not in df.columns:
        print(f"Warning: Column '{col}' not found in the DataFrame. Skipping.")
        columns_to_check.remove(col)

if columns_to_check:
    print("Data types of the (potentially) converted columns:")
    print(df[columns_to_check].dtypes)

    print("\nDescriptive statistics of the (potentially) converted columns:")
    for col in columns_to_check:
        print(f"\nStatistics for column '{col}':")
        print(df[col].describe())
        # Additional check for extremely large or small values
        if df[col].dtype in ['float64', 'int64']:
          min_val = df[col].min()
          max_val = df[col].max()
          print(f"Min value: {min_val}, Max Value: {max_val}")
          if min_val < 0:  # Example check
            print(f"Warning: Negative values found in '{col}'. Further investigation needed.")
          if max_val > 100000: # Example check
            print(f"Warning: Extremely large values found in '{col}'. Further investigation needed.")
else:
    print("No columns to check.")

## Summary:

### Q&A
No questions were posed in the provided data analysis task.

### Data Analysis Key Findings
* No string columns were identified as containing numerical data suitable for conversion to float.  Multiple attempts to find such columns yielded no results.
* The 'Billing Amount' column, which was expected to be numeric, contains negative values, indicating a potential data quality issue.  Further investigation of these negative values is needed.
* The initial data exploration and subsequent attempts to convert columns did not reveal any string columns that could be converted to numeric types.


### Insights or Next Steps
* Investigate the negative values in the 'Billing Amount' column to determine their cause and correct or remove them.
* Re-evaluate the criteria used for identifying potential numeric columns.  The current approach might be too restrictive. Consider expanding the sampling size or employing more sophisticated string-to-number conversion techniques.